import {
    twoPointZero,
    angryBirds2,
    antMan,
    kungFuPanda,
    lego,
    lionKing,
    popeye,
    HP,
    godzilla,
} from '../../assets'

const moviesList = [
    {
        img: kungFuPanda,
        name: 'Kung fu panda',
        certificate: 'U',
        language: 'English',
        description: 'When an obese Po the Panda, a kung fu enthusiast, gets selected as the Dragon Warrior, he decides to team up with the Furious Five and destroy the evil forces that threaten the Valley of Peace',
        rating: 3.75,
        genre: 'Action/ Adventure',
        duration: '1h 37m',
        director: 'Phil Lord',
        year: '2016',
        additionalImages: [
            kungFuPanda,
            antMan,
            lego,
            lionKing,
            popeye,
            HP,
            godzilla,
        ],
    },
    {
        img: HP,
        name: 'Harry Potter',
        certificate: 'U',
        language: 'English',
        description: `Harry Potter is a British-American film series based on the eponymous novels by author J. K. Rowling. The series is distributed by Warner Bros. and consists of eight fantasy films, beginning with Harry Potter and the Philosopher's Stone and culminating with Harry Potter and the Deathly Hallows `,
        rating: 4,
        genre: 'Action/ Adventure',
        duration: '1h 37m',
        director: 'Phil Lord',
        year: '2016',
        additionalImages: [
            HP,
            antMan,
            kungFuPanda,
            lego,
            lionKing,
            popeye,
            HP,
            godzilla,
        ],
    },
    {
        img: angryBirds2,
        name: 'Angry Birds',
        certificate: 'U',
        language: 'English',
        description: 'Red, Chuck, Bomb and the rest of their feathered friends are surprised when a green pig suggests that they put aside their differences and unite to fight a common threat. Aggressive birds from an island covered in ice are planning to use an elaborate weapon to destroy the fowl and swine way of life. After picking their best and brightest, the birds and pigs come up with a scheme to infiltrate the island, deactivate the device and return to their respective paradises intact.',
        rating: 3.5,
        genre: 'Action/ Adventure',
        duration: '1h 37m',
        director: 'Phil Lord',
        year: '2016',
        additionalImages: [
            angryBirds2,
            antMan,
            kungFuPanda,
            lego,
            lionKing,
            popeye,
            HP,
            godzilla,
        ],
    },
    {
        img: lego,
        name: 'Lego',
        certificate: 'U',
        language: 'English',
        description: 'Emmet, an ordinary individual prophesied to be the Special, is entrusted with a huge responsibility of saving the Lego world from the cruel ways of Lord Business.',
        rating: 3.9,
        genre: 'Action/ Adventure',
        duration: '1h 37m',
        director: 'Phil Lord',
        year: '2016',
        additionalImages: [
            lego,
            antMan,
            kungFuPanda,
            lionKing,
            popeye,
            HP,
            godzilla,
        ],
    },
    {
        img: twoPointZero,
        name: '2.0',
        certificate: 'U',
        language: 'Tamil/ Hindi',
        description: `When mobiles start flying from people's hands, Dr Vaseegaran and his robot Nila are asked to help. However, due to Pakshi Rajan having a hand in this, the two have to reinstate Chitti to defeat him.`,
        rating: 3.2,
        genre: 'Action/ Adventure',
        duration: '1h 37m',
        director: 'Phil Lord',
        year: '2016',
        additionalImages: [
            twoPointZero,
            antMan,
            kungFuPanda,
            lego,
            lionKing,
            popeye,
            HP,
            godzilla,
        ],
    },
    {
        img: godzilla,
        name: 'Godzilla 2',
        certificate: 'U',
        language: 'English',
        description: `Members of the crypto-zoological agency Monarch face off against a battery of god-sized monsters, including the mighty Godzilla, who collides with Mothra, Rodan, and his ultimate nemesis, the three-headed King Ghidorah. When these ancient super-species-thought to be mere myths-rise again, they all vie for supremacy, leaving humanity's very existence hanging in the balance.`,
        rating: 4,
        genre: 'Action/ Adventure',
        duration: '1h 37m',
        director: 'Phil Lord',
        year: '2016',
        additionalImages: [
            godzilla,
            antMan,
            kungFuPanda,
            lego,
            lionKing,
            popeye,
            HP,
        ],
    },
    {
        img: antMan,
        name: 'Antman',
        certificate: 'U',
        language: 'English',
        description: 'Criminal Scott gains the ability to shrink in scale with the help of a futuristic suit. Now he must rise to the occasion of his superhero status and protect his secret from unsavoury elements.',
        rating: 3.6,
        genre: 'Action/ Adventure',
        duration: '1h 37m',
        director: 'Phil Lord',
        year: '2016',
        additionalImages: [
            antMan,
            kungFuPanda,
            lego,
            lionKing,
            popeye,
            HP,
            godzilla,
        ],
    },
    {
        img: popeye,
        name: 'Popeye',
        certificate: 'U',
        language: 'English',
        description: 'While in search of his long-lost father, Popeye, a sailor, arrives in a coastal town where he falls in love with Olive Oyl, who is set to be married to Captain Bluto.',
        rating: 2.6,
        genre: 'Action/ Adventure',
        duration: '1h 37m',
        director: 'Phil Lord',
        year: '2016',
        additionalImages: [
            popeye,
            antMan,
            kungFuPanda,
            lego,
            lionKing,
            HP,
            godzilla,
        ],
    },
    {
        img: lionKing,
        name: 'Lion King',
        certificate: 'U',
        language: 'English',
        description: `Simba idolizes his father, King Mufasa, and takes to heart his own royal destiny on the plains of Africa. But not everyone in the kingdom celebrates the new cub's arrival. Scar, Mufasa's brother -- and former heir to the throne -- has plans of his own. The battle for Pride Rock is soon ravaged with betrayal, tragedy and drama, ultimately resulting in Simba's exile. Now, with help from a curious pair of newfound friends, Simba must figure out how to grow up and take back what is rightfully his.`,
        rating: 3.5,
        genre: 'Action/ Adventure',
        duration: '1h 37m',
        director: 'Phil Lord',
        year: '2016',
        additionalImages: [
            lionKing,
            antMan,
            kungFuPanda,
            lego,
            popeye,
            HP,
            godzilla,
        ],
    },
]

export {
    moviesList
}